### ISSUE TITLE
是否愿意多加入一些插件？

### ISSUE THREAD

**Issue by Benjamin23333** [songchenwen/nanopi-r2s#1]
例如网易云解锁三合一和zerotier之类的，提出这两个是这两个我比较常用

**Comment by songchenwen** [comment]
可以考虑。其实更方便的方法是你Fork了自己加，只需要修改 `minimal_config.seed` 并加入以下几行

~~~
CONFIG_PACKAGE_luci-app-unblockmusic=y
CONFIG_UnblockNeteaseMusic_Go=y
CONFIG_UnblockNeteaseMusic_NodeJS=y
CONFIG_PACKAGE_luci-app-zerotier=y
~~~

**Comment by Benjamin23333** [comment]
> 可以考虑。其实更方便的方法是你Fork了自己加，只需要修改 `minimal_config.seed` 并加入以下几行
> 
> ```
> CONFIG_PACKAGE_luci-app-unblockmusic=y
> CONFIG_UnblockNeteaseMusic_Go=y
> CONFIG_UnblockNeteaseMusic_NodeJS=y
> CONFIG_PACKAGE_luci-app-zerotier=y
> ```
还是算了吧，我试过fork别人的项目自己编译，可能因为我是文科专业的关系完全看不懂，触及到了知识盲区，而且编译出错还不知道怎么改，太艰难了，求大佬帮我加上😂

**Comment by songchenwen** [comment]
你说的这两个插件 klever1988 编译的版本里应该是包含的。

https://github.com/klever1988/nanopi-openwrt

**Comment by Benjamin23333** [comment]
> 你说的这两个插件 klever1988 编译的版本里应该是包含的。
> 
> https://github.com/klever1988/nanopi-openwrt

这个项目里的固件暂时插usb无线网卡会死机，我在寻找替代，你的friendlywrt版固件我测试无线没有问题，但是我常用的那两个插件又没有，所以我就问一下可不可以添加

**Comment by songchenwen** [comment]
加了新的 FwF 版本，里面包含一堆插件，GitHub 正在编译，如果没出错的话，2小时后应该能在 Release 里看到了，要是出错了我再看看咋改。

**Comment by Benjamin23333** [comment]
> 加了新的 FwF 版本，里面包含一堆插件，GitHub 正在编译，如果没出错的话，2小时后应该能在 Release 里看到了，要是出错了我再看看咋改。

谢谢大佬

**Comment by songchenwen** [comment]
如果能编译过的话，你可以刷刷试试，我现在跑的挺稳的，就不刷这个版本了。

**Comment by songchenwen** [comment]
@Benjamin23333 编译好了亲，如果测试中有问题的话，提新 Issue 吧，这个我关了

**Comment by songchenwen** [comment]
> > 加了新的 FwF 版本，里面包含一堆插件，GitHub 正在编译，如果没出错的话，2小时后应该能在 Release 里看到了，要是出错了我再看看咋改。
> 
> 谢谢大佬

试的怎么样？有结果希望能反馈一下

**Comment by Benjamin23333** [comment]
> > > 加了新的 FwF 版本，里面包含一堆插件，GitHub 正在编译，如果没出错的话，2小时后应该能在 Release 里看到了，要是出错了我再看看咋改。
> > 
> > 
> > 谢谢大佬
> 
> 试的怎么样？有结果希望能反馈一下

刚刷，昨天晚上做数学题了，刷完之后连不上网，我整个人傻了，看接口，wan口拨号拨通了，然而网页打不开，所有插件也连不上网，软件包刷新不了。然后我重启了一下，网可以上了，但是所有插件还是都连不上网

**Comment by songchenwen** [comment]
😯搞砸了

**Comment by songchenwen** [comment]
>然后我重启了一下，网可以上了，但是所有插件还是都连不上网

@Benjamin23333 是说的 PassWall 里百度和谷歌都测试失败吗？

这种情况的话看一下 README 里说的，更新一下 wget

**Comment by Benjamin23333** [comment]
> > 然后我重启了一下，网可以上了，但是所有插件还是都连不上网
> 
> @Benjamin23333 是说的 PassWall 里百度和谷歌都测试失败吗？
> 
> 这种情况的话看一下 README 里说的，更新一下 wget

不是，opkg update也就是刷新软件包无法运行的，返回的全是下载失败，所有插件都是连不上网的

**Comment by songchenwen** [comment]
我有空的时候刷一下看看吧

**Comment by Benjamin23333** [comment]
> 我有空的时候刷一下看看吧

好，那我还是继续用kl的吧，没有无线就暂时不用无线吧😂

**Comment by songchenwen** [comment]
opkg 不能更新的问题最新版已修复好

**Comment by Benjamin23333** [comment]
> opkg 不能更新的问题最新版已修复好

其他插件连不上网的问题也解决了么？

**Comment by songchenwen** [comment]
不知道什么叫其他插件连不上网。我试的PassWall，AdguardHome和ServerChan都能连上网。你说的其他插件指什么？

**Comment by Benjamin23333** [comment]
> 不知道什么叫其他插件连不上网。我试的PassWall，AdguardHome和ServerChan都能连上网。你说的其他插件指什么？

我是不是应该等你今天的fw_update的版本出来再刷比较好？你这个更新是不是从你的可以更新到其他人的固件？更新成其他人的还回得来么？还有，更新保留配置么？

**Comment by songchenwen** [comment]
等不等都行。但是要等的话可能时间会比较久，github的action坏了，他们正在修。fw_update就是scripts文件夹里对应的文件，理论上放到哪个 R2S 的ROM里，只要依赖装好，都能运行，不过我没试过别人的ROM。更新是保留配置的，但是配置能不能兼容就不知道了，这取决于你都具体都装了哪些包，这些包的配置是否兼容，openwrt的更新都会面临这个问题。

**Comment by Benjamin23333** [comment]
> 等不等都行。但是要等的话可能时间会比较久，github的action坏了，他们正在修。fw_update就是scripts文件夹里对应的文件，理论上放到哪个 R2S 的ROM里，只要依赖装好，都能运行，不过我没试过别人的ROM。更新是保留配置的，但是配置能不能兼容就不知道了，这取决于你都具体都装了哪些包，这些包的配置是否兼容，openwrt的更新都会面临这个问题。

意思是wget -qO- fw_update的脚本url，然后执行你给的fw_update命令也可以么？（不知道我写的对不对，我看kl的那个更新命令套的）

**Comment by songchenwen** [comment]
就 wget ‘https://raw.githubusercontent.com/songchenwen/nanopi-r2s/master/scripts/fw_update.sh’ 把它下载到路由器上再执行就行。或者你也可以用电脑下载了再把它上传到路由器里。

**Comment by Benjamin23333** [comment]
> 就 wget ‘[https://raw.githubusercontent.com/songchenwen/nanopi-r2s/master/scripts/fw_update.sh’](https://raw.githubusercontent.com/songchenwen/nanopi-r2s/master/scripts/fw_update.sh%E2%80%99) 把它下载到路由器上再执行就行。或者你也可以用电脑下载了再把它上传到路由器里。

要放到root文件夹里是么？

**Comment by songchenwen** [comment]
放哪都行，我选择放在 /usr/bin里

**Comment by Benjamin23333** [comment]
> 放哪都行，我选择放在 /usr/bin里

好，明白了，谢谢指导
