### ISSUE TITLE
FwF-2020-05-20-b0a8b83版frp无法使用

### ISSUE THREAD

**Issue by xinlonzh** [songchenwen/nanopi-r2s#12]
frp服务端与客户端版本一致，启动报错： frp服务启动失败，请检查服务端 “TCP多路复用(tcp_mux)”设置，确保与客户端完全一致！经检查确认客户端与服务端tcp_mux均为true，希望能在下个版本中修复，谢谢！

**Comment by viccom** [comment]
下个最新版的frpc arm64版本上传覆盖/usr/bin/下的同名文件就可使用了

**Comment by xinlonzh** [comment]
问题解决，谢谢！
