### ISSUE TITLE
想请教一下您是如何让netdata显示温度的？

### ISSUE THREAD

**Issue by xuealan** [songchenwen/nanopi-r2s#14]
用klever1988的版本netdata没有cpu温度显示，不知道在哪儿改，向您求教，谢谢！

**Comment by songchenwen** [comment]
看[这段代码](https://github.com/songchenwen/nanopi-r2s/blob/e61ce17555e09a38890c2f8d79d1099803b35b0b/.github/workflows/friendlywrt.yml#L135)
