### ISSUE TITLE
fwf版本还是有bug

### ISSUE THREAD

**Issue by Benjamin23333** [songchenwen/nanopi-r2s#2]
![image](https://user-images.githubusercontent.com/54323063/79059063-195b8680-7ca8-11ea-9dbb-52f2c15a3d28.png)
![image](https://user-images.githubusercontent.com/54323063/79059081-6d666b00-7ca8-11ea-8f0f-70c542acbf54.png)
这两个扶墙插件在同一时间出现了这两个状况

**Comment by songchenwen** [comment]
连在路由下的电脑实际能访问百度谷歌吗？

**Comment by Benjamin23333** [comment]
> 连在路由下的电脑实际能访问百度谷歌吗？

电脑可以访问百度之类的国内网站，但是不更新gfw和chn的话，也无法翻墙啊，而且我看到你这个固件里好像还没有v2ra😂

**Comment by songchenwen** [comment]
电脑能访问的话应该是路由器上的wget版本旧，升级一下应该就好了。你说的v2ray是哪个包？能提供下包名的话我下版本加上。

**Comment by Benjamin23333** [comment]
> 电脑能访问的话应该是路由器上的wget版本旧，升级一下应该就好了。你说的v2ray是哪个包？能提供下包名的话我下版本加上。

这个。。v2ray安装和设置相关的语句可能有点多。。。

**Comment by songchenwen** [comment]
我待会自己查查吧，顺便看看能不能解决wget这个问题

**Comment by Benjamin23333** [comment]
> 我待会自己查查吧，顺便看看能不能解决wget这个问题

我试试

**Comment by Benjamin23333** [comment]
> 我待会自己查查吧，顺便看看能不能解决wget这个问题

wget的事解决了，我发现你这个固件里有v2ray，但是好像是ssr+可以调用，passwall调用不了

**Comment by songchenwen** [comment]
我自己不用v2ray，所以没试过。PassWall的逻辑是只要能在系统bin目录里找到对应模块的执行文件就会开启对应的模块，可能可以通过把 ssr+的v2ray link过来的方式解决。

**Comment by songchenwen** [comment]
很奇怪的是，我自己刷的FriendlyWRT版的 PassWall是能开启v2ray的。

**Comment by songchenwen** [comment]
难道这俩插件在一起还闹脾气了？不过现在这样是不是也足够拿来用了？我的刷了FriendlyWRT版的R2S昨天下午已经放进弱电箱当主路由了。最近不打算再刷ROM了，想看看它一直不重启能稳定运行多久。

**Comment by Benjamin23333** [comment]
> 难道这俩插件在一起还闹脾气了？不过现在这样是不是也足够拿来用了？我的刷了FriendlyWRT版的R2S昨天下午已经放进弱电箱当主路由了。最近不打算再刷ROM了，想看看它一直不重启能稳定运行多久。

如果说普通的上网需求倒是没问题，然而翻墙全都无法使用了，我在上面总结了三个bug，不知道你能不能看到

**Comment by Benjamin23333** [comment]
> 难道这俩插件在一起还闹脾气了？不过现在这样是不是也足够拿来用了？我的刷了FriendlyWRT版的R2S昨天下午已经放进弱电箱当主路由了。最近不打算再刷ROM了，想看看它一直不重启能稳定运行多久。

要不然就把ssr+去掉吧，顺便把多拨也去掉，听说多拨去掉可以提升性能

**Comment by songchenwen** [comment]
都是好奇怪的问题。想不到原因。要不我下次把 ssr+去掉试试吧。我还是觉得装的包越少越稳。选PassWall不选ssr+是因为支持按端口号设置访问控制，nas下bt需要。我后边再精简一下FwF吧，最开始一下子加入太多包了。

不过我最近不刷机测了，你要是想测就测测，有问题我就再看看能不能修。不想测就放着也行，估计也没啥人用。

**Comment by Benjamin23333** [comment]
> 都是好奇怪的问题。想不到原因。要不我下次把 ssr+去掉试试吧。我还是觉得装的包越少越稳。选PassWall不选ssr+是因为支持按端口号设置访问控制，nas下bt需要。我后边再精简一下FwF吧，最开始一下子加入太多包了。
> 
> 不过我最近不刷机测了，你要是想测就测测，有问题我就再看看能不能修。不想测就放着也行，估计也没啥人用。

好

**Comment by songchenwen** [comment]
你要不关了代理更新下v2ray试试？我刚看了一下，我这也不显示v2ray版本号，但是我点手动更新下载了之后就有版本号了。可能确实就是固件里本来就没编译进去v2ray

![image](https://user-images.githubusercontent.com/6240753/79060174-68a7b400-7cb4-11ea-9c1e-0a190bda1607.jpeg)

**Comment by songchenwen** [comment]
Clash不香吗？各种路由规则，各种自动切换节点。玩到起飞。

**Comment by Benjamin23333** [comment]
> 你要不关了代理更新下v2ray试试？我刚看了一下，我这也不显示v2ray版本号，但是我点手动更新下载了之后就有版本号了。可能确实就是固件里本来就没编译进去v2ray
> 
> ![image](https://user-images.githubusercontent.com/6240753/79060174-68a7b400-7cb4-11ea-9c1e-0a190bda1607.jpeg)

没为没开起来代理😂，我不是说了ssr+和pw都无法运行的了么😂

**Comment by songchenwen** [comment]
无法启动是不能启动v2ray，但没准iptables规则已经插入了，这可能会导致你没办法更新binary。

或者你就用Clash，它也支持配置v2ray节点。

**Comment by Benjamin23333** [comment]
> 无法启动是不能启动v2ray，但没准iptables规则已经插入了，这可能会导致你没办法更新binary。
> 
> 或者你就用Clash，它也支持配置v2ray节点。

那我找时间再试试吧

**Comment by Benjamin23333** [comment]
> 无法启动是不能启动v2ray，但没准iptables规则已经插入了，这可能会导致你没办法更新binary。
> 
> 或者你就用Clash，它也支持配置v2ray节点。

我刚刚刷了你的fwf，bug已经没有了，非常感谢，如果有可能的话fwf版本可以再加入acc加速么？这个对网速和nat能力真的有很大提升

**Comment by songchenwen** [comment]
那我先close这个了。acc不是据说在R2S上还不稳定吗？我想的是等后续看别人反馈稳定了再上。毕竟我这一家老小的断网就要炸了。而且我跑了几天，实测不开acc性能也够。

**Comment by songchenwen** [comment]
还有FwF这个固件，可不可以拜托你用几天后给我反馈一下，稳定性足不足以让我把它列为推荐固件？ @Benjamin23333

**Comment by Benjamin23333** [comment]
> 那我先close这个了。acc不是据说在R2S上还不稳定吗？我想的是等后续看别人反馈稳定了再上。毕竟我这一家老小的断网就要炸了。而且我跑了几天，实测不开acc性能也够。

应为kl的有acc，用习惯了，是不能单独对某个版本添加特定插件么？如果你能的话可不可以给fwf版本单独添加呢？如果不能，您还担心的出问题的话，就不用了

**Comment by Benjamin23333** [comment]
> 还有FwF这个固件，可不可以拜托你用几天后给我反馈一下，稳定性足不足以让我把它列为推荐固件？ @Benjamin23333

也就是要我用几天而且不能更新是么？

**Comment by songchenwen** [comment]
> > 还有FwF这个固件，可不可以拜托你用几天后给我反馈一下，稳定性足不足以让我把它列为推荐固件？ @Benjamin23333
> 
> 也就是要我用几天而且不能更新是么？

没有强制要求，你随便用，只是最后能给我一个反馈就好了。因为这个版本我自己没刷，装的包我也精简了之后，我觉得应该会比较稳定了

**Comment by songchenwen** [comment]
> > 那我先close这个了。acc不是据说在R2S上还不稳定吗？我想的是等后续看别人反馈稳定了再上。毕竟我这一家老小的断网就要炸了。而且我跑了几天，实测不开acc性能也够。
> 
> 应为kl的有acc，用习惯了，是不能单独对某个版本添加特定插件么？如果你能的话可不可以给fwf版本单独添加呢？如果不能，您还担心的出问题的话，就不用了

因为基于FriendlyWRT的这两个版本，我对它们的定位是求稳的。希望能做到让人可以放心的当家庭主路由用的，毕竟就算自己再爱折腾，也不能折腾家人啊。所以在有人反馈不稳定的情况下，我还是不想加入acc来。

**Comment by Benjamin23333** [comment]
> > > 那我先close这个了。acc不是据说在R2S上还不稳定吗？我想的是等后续看别人反馈稳定了再上。毕竟我这一家老小的断网就要炸了。而且我跑了几天，实测不开acc性能也够。
> > 
> > 
> > 应为kl的有acc，用习惯了，是不能单独对某个版本添加特定插件么？如果你能的话可不可以给fwf版本单独添加呢？如果不能，您还担心的出问题的话，就不用了
> 
> 因为基于FriendlyWRT的这两个版本，我对它们的定位是求稳的。希望能做到让人可以放心的当家庭主路由用的，毕竟就算自己再爱折腾，也不能折腾家人啊。所以在有人反馈不稳定的情况下，我还是不想加入acc来。

我妈睡得比较早，我也是每天趁他睡觉了，更新下当天新出的固件

**Comment by songchenwen** [comment]
> 我妈睡得比较早，我也是每天趁他睡觉了，更新下当天新出的固件

我家我是睡得最早的。。。

**Comment by Benjamin23333** [comment]
> > 我妈睡得比较早，我也是每天趁他睡觉了，更新下当天新出的固件
> 
> 我家我是睡得最早的。。。

我刚才发现一个小问题，在网页刷新软件包不行，会出现bad啥啥啥的那个页面，我又试了下ssh下opkg update 可以用，难道是我刷的时候没刷好？

**Comment by songchenwen** [comment]
> 我刚才发现一个小问题，在网页刷新软件包不行，会出现bad啥啥啥的那个页面，我又试了下ssh下opkg update 可以用，难道是我刷的时候没刷好？

这。。。你网页上点刷新实际上后台也是调用的 opkg update。理论上效果是一样的。可能正好你点的时候网络不稳定？

**Comment by Benjamin23333** [comment]
> > 我刚才发现一个小问题，在网页刷新软件包不行，会出现bad啥啥啥的那个页面，我又试了下ssh下opkg update 可以用，难道是我刷的时候没刷好？
> 
> 这。。。你网页上点刷新实际上后台也是调用的 opkg update。理论上效果是一样的。可能正好你点的时候网络不稳定？

也许吧

**Comment by Benjamin23333** [comment]
> > 我刚才发现一个小问题，在网页刷新软件包不行，会出现bad啥啥啥的那个页面，我又试了下ssh下opkg update 可以用，难道是我刷的时候没刷好？
> 
> 这。。。你网页上点刷新实际上后台也是调用的 opkg update。理论上效果是一样的。可能正好你点的时候网络不稳定？

我好像找到原因了。。你更新软件包的命令里有一条check的命令，可能check了一遍实践比较长，然后被认为是超时了？

**Comment by songchenwen** [comment]
> 我好像找到原因了。。你更新软件包的命令里有一条check的命令，可能check了一遍时间比较长，然后被认为是超时了？

有可能。这个界面也不是我做的，对应的包是Lean大的，我觉得一般应该也不会有人改这个界面吧，所以估计官方openwrt也是这样的。不过不是什么大问题，不影响使用就行了。

**Comment by Benjamin23333** [comment]
> > 我好像找到原因了。。你更新软件包的命令里有一条check的命令，可能check了一遍时间比较长，然后被认为是超时了？
> 
> 有可能。这个界面也不是我做的，对应的包是Lean大的，我觉得一般应该也不会有人改这个界面吧，所以估计官方openwrt也是这样的。不过不是什么大问题，不影响使用就行了。

昨天怎么没有更新😂，我不是催更，只是突然又一天没更新有点不习惯，18号的fwf我从18号下午两点用到现在，感觉没什么问题，就是会突然网没了，伴随着所有局域网设备（包括一二级路由，nas）全都访问不了了，然后过几秒钟还是十几秒钟就好了，也不知道怎么回事，就出现了一次，会和作为主路由的r2s有关么？

**Comment by songchenwen** [comment]
降低了更新频率，fwf github action 每周自动运行一次，天天更新没意义，上游也没那么多可更新的。

**Comment by Benjamin23333** [comment]
> 降低了更新频率，fwf github action 每周自动运行一次，天天更新没意义，上游也没那么多可更新的。

这样啊，好的

**Comment by songchenwen** [comment]
> 就是会突然网没了，伴随着所有局域网设备（包括一二级路由，nas）全都访问不了了，然后过几秒钟还是十几秒钟就好了，也不知道怎么回事，就出现了一次，会和作为主路由的r2s有关么？

故障对应时间的系统日志如果能发来看一下，可能有助于定位这个问题。
