### ISSUE TITLE
成功开启 Flow Offload 的方法

### ISSUE THREAD

**Issue by fanck0605** [songchenwen/nanopi-r2s#3]
不能开启 flow offload 的主要还是内核配置的问题
openwrt 的 rootfs 上层组件都是全的，但是 kernel 的组件不全（主要是 神奇的友善 搞了两套 sdk 编译？？？）

这么操作，测下来 PPPoE 可以完美运行。

1. 使用已经 patch 内核补丁，但未修改过 `kernel/arch/arm64/configs/nanopi-r2_linux_defconfig` 的源码编译一遍（主要用来生成  `.config`）
2. 取出 rockchip 的内核配置 `kernel/.config` 作为 `rk_config`
3. 取出 openwrt 的内核配置 `friendlywrt/toolchain-aarch64_cortex-a53_gcc-*/linux/.config` 作为 `op_config`
4. 手动删一下 `op_config` 多余内容，只保留 `Networking options` 部分
5. 使用 [我的脚本](https://github.com/fanck0605/nanopi-r2s/blob/lean/scripts/MergeKernelConfig.java) 将 `op_config` 的 `Networking options` 部分 merge 到 `rk_config`
6. 将 `rk_config` 放回 kernel/.config
7. 将 kernel 的编译平台设置为 arm64，重新导出 `defconfig`
   ```
   export PATH=/opt/FriendlyARM/toolchain/6.4-aarch64/bin/:$PATH
   export CROSS_COMPILE='aarch64-linux-gnu-'
   export ARCH=arm64
   make savedefconfig
   ```
8. 至此，在 kernel 目录下会有一个 `defconfig`，复制到 `kernel/arch/arm64/configs/nanopi-r2_linux_defconfig`，就完成了，当然废了那么大功夫别忘了保存下来。

**Comment by songchenwen** [comment]
😮 ，这么复杂，看来这两天你真是做了不少尝试啊

**Comment by fanck0605** [comment]
https://github.com/fanck0605/kernel-rockchip/blob/nanopi-r2-v5.4.y/arch/arm64/configs/nanopi-r2_linux_defconfig
你可以试一下直接用我的配置稳不稳定。

**Comment by songchenwen** [comment]
这两天有点忙，还没顾上试，主要是家里也不敢断网😞 ，一有机会我一定试一下

**Comment by songchenwen** [comment]
更新用上你的kernel项目了 @fanck0605  👍

**Comment by gyj1109** [comment]
@fanck0605 使用您最新的5.4.37内核[编译时报如下错误](https://github.com/gyj1109/R2S/runs/638918096)：
```
Patch failed!  Please fix target/linux/octeontx/patches-5.4/0004-PCI-add-quirk-for-Gateworks-PLX-PEX860x-switch-with-.patch!
```
请问该如何改正？谢谢！

顺便 @songchenwen ，是和编译脚本有关吗？

**Comment by fanck0605** [comment]
> @fanck0605 使用您最新的5.4.37内核[编译时报如下错误](https://github.com/gyj1109/R2S/runs/638918096)：
> 
> ```
> Patch failed!  Please fix target/linux/octeontx/patches-5.4/0004-PCI-add-quirk-for-Gateworks-PLX-PEX860x-switch-with-.patch!
> ```
> 
> 请问该如何改正？谢谢！
> 
> 顺便 @songchenwen ，是和编译脚本有关吗？

等待 Openwrt 更新 5.4.37 的补丁，明天就差不多更新了。
或者暂时注释这一行，将就着编译
```
./scripts/patch-kernel.sh ../kernel target/linux/octeontx/patches-5.4
```
