### ISSUE TITLE
问个Clash的使用问题

### ISSUE THREAD

**Issue by pafans** [songchenwen/nanopi-r2s#5]
刷了老哥魔改的新passwall固件，但是没研究出来Clash要怎么用。我把OC的Clash配置导出后贴到passwall的Clash创建窗口，然后把tcp节点切换到新建的OC节点，重启passwalll，但是不起作用，老哥请指点迷津

**Comment by songchenwen** [comment]
有几点要注意的:

1. clash dns 要开启并 listen: 0.0.0.0:7913
2. clash dns.enhanced-mode 设置成 redir host 模式 
3. clash dns.nameserver 要指定可直接访问的 dns
4. passwall 基本设置里两个dns都指向本机7913端口
5. udp 转发我没试过，目前可能有些问题

**Comment by pafans** [comment]
修改了, 但是依然没效果, 如果要排错的话, 建议如何入手? 目前没有看到任何有用的日志信息
或者能否给出一个配置文件的样本?

**Comment by songchenwen** [comment]
## 配置示例

~~~
# port of SOCKS5
socks-port: 3456

# redir proxy for Linux and macOScat
redir-port: 1041

allow-lan: true

# Rule / Global/ Direct (default is Rule)
mode: Rule

# set log level to stdout (default is info)
# info / warning / error / debug
log-level: debug

# A RESTful API for clash
external-controller: 0.0.0.0:9090

dns:
 enable: true # set true to enable dns (default is false)
 ipv6: false # default is false
 listen: 0.0.0.0:7913
 enhanced-mode: redir-host
 nameserver:
  - 114.114.114.114 # change this to your isp dns. `cat /tmp/resolv.conf.auto`
 fallback: # concurrent request with nameserver, fallback used when GEOIP country isn't CN
  - https://1.1.1.1/dns-query #Cloudflare
  - tls://8.8.8.8:853 #Google
 fallback-filter:
  geoip: true
  ipcidr: # ips in these subnets will be considered polluted
   - 240.0.0.0/4
   - 0.0.0.0/4
~~~

<img width="587" alt="截屏2020-05-04 下午12 01 26" src="https://user-images.githubusercontent.com/6240753/80935413-1400e000-8dff-11ea-8657-5d9da21064e3.png">

## 排错方法

基本上只会遇到两种问题，clash 执行失败，或者dns出问题，以下需 ssh 操作

1. `ps | grep clash` 看 clash 是否在执行，如果没有执行，说明 clash 配置文件有问题
2. 如果发现 clash 没有执行，手动运行 `clash -d /etc/clash`，查看报错，并调整配置文件
3. 再用 `sudo -u nobody clash -d /etc/clash` 运行 clash, 检查配置文件权限
4. `nslookup -p7913 google.com` 和 `nslookup google.com` 分别确认 clash 的 dns 和 dnsmasq 的 dns 是否运行正常
5. 防火墙自定义规则可以添加以下两行来保证 fallback dns 走代理

~~~
iptables -t nat -I OUTPUT -d 1.1.1.1/32 -p tcp -j REDIRECT --to-ports 1041
iptables -t nat -I OUTPUT -d 8.8.0.0/16 -p tcp -j REDIRECT --to-ports 1041
~~~

6. 防火墙自定义规则如果有以下两行的话，可以把它们删掉

~~~
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
~~~

**Comment by pafans** [comment]
非常感谢指导, 主要问题已经解决
配置文件有一处空格没有对齐, 导致clash无法正常启动
fallback的dns不能访问, 加完规则也不行, 先找了临时替代方案来解决, 但是分流已经没有问题了
谢谢!
