### ISSUE TITLE
系统日志显示丢失ujail

### ISSUE THREAD

**Issue by aisubing** [songchenwen/nanopi-r2s#6]
FriendlyWrt版本（4.28、4.29、5.1），做二级路由，动态ip
错误日志：daemon.err procd: unable to find /sbin/ujail: No such file or directory (-1)
目前未发现可见影响

**Comment by songchenwen** [comment]
这个不影响 

http://lists.infradead.org/pipermail/openwrt-devel/2020-January/021508.html
