### ISSUE TITLE
防火墙里开启FullCone-NAT后在Turbo ACC中显示未运行？

### ISSUE THREAD

**Issue by gyj1109** [songchenwen/nanopi-r2s#7]
用的是4.30版，README中说加入了FullCone-NAT，但貌似不能用。

**Comment by fanck0605** [comment]
@songchenwen luci 配置的确可能不生效，需要给防火墙打上这个补丁，在 lean 的 OpenWrt 里也有
https://github.com/LGA1150/fullconenat-fw3-patch
